name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: xcodebuild
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: burstcamp/burstcamp.xcodeproj
          scheme: burstcamp
          destination: platform=iOS
          action: build
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict --config "burstcamp/.swiftlint.yml"
        env:
          DIFF_BASE: ${{ github.base_ref }}
        
