name: build

on:
  push:
    branches: [ develop, feature/*, refactor/*, fix/* ]
  pull_request:
    branches: [ main, develop ]

env:
  PROJECT: 'burstcamp/burstcamp'

jobs:
  build:
    runs-on: macos-11
    strategy:
        matrix:
          include:
            - xcode: "12.4"
              ios: "14.4"
              simulator: "iPhone 12 Pro"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Create secret file
      env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
          API_SECRET: ${{ secrets.API_SECRET }}
      run: |
        echo $FIREBASE_SECRET | base64 -D -o ${{ env.PROJECT }}/GoogleService-Info.plist
        echo $API_SECRET | base64 -D -o ${{ env.PROJECT }}/Service-Info.plist

    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode}}.app && /usr/bin/xcodebuild -version

    - name: Cache SwiftPM
      uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-xcode_${{ matrix.xcode }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-xcode_${{ matrix.xcode }}-spm-

    - name: Cache DerivedData
      uses: actions/cache@v1
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-iOS_derived_data-xcode_${{ matrix.xcode }}
        restore-keys: |
          ${{ runner.os }}-iOS_derived_data-
  
    - name: Build
      run: |
        xcodebuild clean build -project ${{ env.PROJECT }}.xcodeproj -scheme burstcamp -destination 'platform=iOS Simulator,OS=${{ matrix.ios }},name=${{ matrix.simulator }}'