name: build

on:
  push:
    branches: [ develop, feature/*, refactor/*, fix/* ]
  pull_request:
    branches: [ main, develop ]
env:
  PROJECT: 'burstcamp/burstcamp'
jobs:
  build:
    runs-on: macos-11
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 13 Pro']

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Create secret file
      env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
          API_SECRET: ${{ secrets.API_SECRET }}
      run: |
        echo $FIREBASE_SECRET | base64 -D -o ${{ env.PROJECT }}/GoogleService-Info.plist
        echo $API_SECRET | base64 -D -o ${{ env.PROJECT }}/Service-Info.plist

    - name: Build
      run: |
        xcodebuild clean build -project ${{ env.PROJECT }}.xcodeproj -scheme burstcamp -destination "${{ matrix.destination }}"