name: build

on:
  push:
    branches: [ develop, feature/*, refactor/*, fix/* ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 13 Pro']
    env:
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        API_SECRET: ${{ secrets.API_SECRET }}
        PROJECT: 'burstcamp/burstcamp'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Create secret file
      
      run: |
        echo $FIREBASE_SECRET | base64 -D -o $PROJECT/GoogleService-Info.plist
        echo $API_SECRET | base64 -D -o $PROJECT/Service-Info.plist

    - name: Build
      run: |
        xcodebuild clean build -project $PROJECT.xcodeproj -scheme burstcamp -destination "${destination}"